# Exercise 1.A NumPy: Manipulating Arrays

In [15]:
import numpy as np

In [16]:
numbers = np.array([10, 20, 30, 40, 50])
print(numbers)

[10 20 30 40 50]


In [17]:
print(numbers.shape)

(5,)


In [18]:
print(numbers.dtype)

int64


In [19]:
print(numbers[0])
print(numbers[-1])
print(numbers[1:4])

10
50
[20 30 40]


In [20]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

for x in arrA:
    print(x * 2)

for x in arrA:
    for y in x:
        print(y * 2)

[[11 12 13]
 [14 15 16]]
[22 24 26]
[28 30 32]
22
24
26
28
30
32


In [21]:
loop_result = []

for x in arrA:
    for y in x:
        loop_result.append(y * 2)

print(loop_result)

[np.int64(22), np.int64(24), np.int64(26), np.int64(28), np.int64(30), np.int64(32)]


The first loop worked row by row, while the nested loop worked through each individual number inside the array.

In [22]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [23]:
stacked_array = np.stack((arrA, arrA))
print(stacked_array)

horizontal_stack = np.hstack((arrA, arrA))
print(horizontal_stack)

vertical_stack = np.vstack((arrA, arrA))
print(vertical_stack)

[[[11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]]]
[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [24]:
split_array = np.array_split(horizontal_stack, 2)
print(split_array)

[array([[11, 12, 13, 11, 12, 13]]), array([[14, 15, 16, 14, 15, 16]])]


In [25]:
print(split_array[0])
print(split_array[1])

[[11 12 13 11 12 13]]
[[14 15 16 14 15 16]]


In [26]:
sample = np.array([4, 9, 4, 8, 0, 6])

result = np.where(sample < 5)
print(result)

changed = np.where(sample < 5, sample, sample * 0.9)
print(changed)

(array([0, 2, 4]),)
[4.  8.1 4.  7.2 0.  5.4]


In [28]:
unsorted = np.array([14, 9, 4, 18, 0, 6])

print(np.sort(unsorted))

filtered = unsorted[unsorted > 10]
print(filtered)

[ 0  4  6  9 14 18]
[14 18]
