# Exercise 1.B NumPy: Random Numbers

In [1]:
import numpy as np

## Generating Random Numbers

In [8]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)

r_3 = np.random.rand(2, 1)
print(r_3)

r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

r_5 = np.random.rand(4, 5)
print(r_5)

[15 14]
[[16 20]]
[[0.44427602]
 [0.9325688 ]]
[[77 66 94 39 27]
 [58 54 78 62 73]
 [63 26 23 42 84]
 [23 90 66 74 59]]
[[0.19960938 0.51784568 0.97046211 0.02696268 0.56861172]
 [0.34868619 0.82987888 0.39640731 0.77415767 0.84239308]
 [0.31920727 0.70298219 0.46254164 0.65884969 0.99423634]
 [0.54201924 0.94205937 0.82001508 0.66775671 0.36267794]]


## Generating Random Choices from an Array

In [9]:
students = np.array([
    "Hannah", "Sally", "Luis", "Alexis",
    "Corey", "Blake", "Leslie", "Livrata",
    "Charles", "Grace", "Ken", "Dagmawi"
])

call_on = np.random.choice(students)
print(call_on)

breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)

# This may not be the best way to assign breakout groups because the same student can be selected more than once.

Ken
[['Alexis' 'Sally' 'Corey' 'Luis']
 ['Livrata' 'Grace' 'Grace' 'Leslie']
 ['Corey' 'Sally' 'Dagmawi' 'Ken']]


In [10]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.15, 0.10, 0.10, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.00]
)

print(call_on_weighted)

# Hannah has a 30% chance of being selected, Dagmawi has a 0% chance, and the other students have smaller probability values.

['Sally' 'Blake' 'Alexis' 'Hannah' 'Hannah']


## Generating a Normal Distribution

In [11]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[12.45762993 10.52162849  9.2056672   3.01371335  5.72448327]
 [10.21579843  2.16951384 11.5604261   5.42507924 11.03431134]
 [10.63978237 16.44383119 11.37230512  2.96745967 11.86777729]
 [ 3.87422374  9.28072012  7.14506625  2.91050434 -2.99761409]]
