# Exercise 1.C Performing operations on arrays

In [8]:
import numpy as np

## Sample Arrays

In [9]:
r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.rand(4, 5)

print(r_1)
print(r_2)
print(r_3)
print(r_4)
print(r_5)

[14 17]
[[3 1]]
[[0.80698105]
 [0.60110531]]
[[45 38 61 69 44]
 [77 75 78 86 53]
 [94 67 88 94 93]
 [53 72 61 37 71]]
[[0.64289958 0.41761303 0.84897772 0.14564775 0.69196124]
 [0.8159391  0.97600223 0.10710285 0.03235568 0.21268127]
 [0.8495173  0.09206259 0.43595606 0.301172   0.87674195]
 [0.32707781 0.76107667 0.52670093 0.84883233 0.88070817]]


## Permutations

In [10]:
print(r_4)

np.random.shuffle(r_4)
print(r_4)

[[45 38 61 69 44]
 [77 75 78 86 53]
 [94 67 88 94 93]
 [53 72 61 37 71]]
[[94 67 88 94 93]
 [45 38 61 69 44]
 [53 72 61 37 71]
 [77 75 78 86 53]]


The shuffle function changed the order of the rows in r_4 directly. It modifies the original array in place.

In [11]:
new_shuffle = np.random.permutation(r_4)

print(new_shuffle)
print(r_4)

[[94 67 88 94 93]
 [53 72 61 37 71]
 [77 75 78 86 53]
 [45 38 61 69 44]]
[[94 67 88 94 93]
 [45 38 61 69 44]
 [53 72 61 37 71]
 [77 75 78 86 53]]


I would use shuffle when I want to change the original array. I would use permutation when I want a new shuffled copy while keeping the original array unchanged.

## Mathematical Operations

In [12]:
print(r_1)
print(r_1.shape)

print(r_2)
print(r_2.shape)

result = np.add(r_1, r_2)
print(result)
print(result.shape)

[14 17]
(2,)
[[3 1]]
(1, 2)
[[17 18]]
(1, 2)


In [13]:
print(r_1)
print(r_1.shape)

print(r_3)
print(r_3.shape)

result = np.add(r_1, r_3)
print(result)
print(result.shape)

[14 17]
(2,)
[[0.80698105]
 [0.60110531]]
(2, 1)
[[14.80698105 17.80698105]
 [14.60110531 17.60110531]]
(2, 2)


In [16]:
print(r_2)
print(r_2.shape)

print(r_4)
print(r_4.shape)

result = np.add(r_4, np.array([1, 1, 1, 1, 1]))
print(result)
print(result.shape)

[[3 1]]
(1, 2)
[[94 67 88 94 93]
 [45 38 61 69 44]
 [53 72 61 37 71]
 [77 75 78 86 53]]
(4, 5)
[[95 68 89 95 94]
 [46 39 62 70 45]
 [54 73 62 38 72]
 [78 76 79 87 54]]
(4, 5)


# Adding r_1 to r_4 gives an error because their shapes do not match for broadcasting.
# r_2 can be added to r_4 because r_2 has 1 row and 2 columns, but r_4 has 4 rows and 5 columns, so this may also create a shape error.
# r_3 can be added to r_4 because r_3 has 2 rows and 1 column, but r_4 has 4 rows and 5 columns, so this also may not broadcast correctly.

print(np.add(r_1, r_4))

In [17]:
print(r_4 + np.array([1]))

[[95 68 89 95 94]
 [46 39 62 70 45]
 [54 73 62 38 72]
 [78 76 79 87 54]]


In [18]:
print(r_4 + np.array([[1]]))

[[95 68 89 95 94]
 [46 39 62 70 45]
 [54 73 62 38 72]
 [78 76 79 87 54]]


In [19]:
print(r_4 + np.array([1, 1, 1, 1, 1]))

[[95 68 89 95 94]
 [46 39 62 70 45]
 [54 73 62 38 72]
 [78 76 79 87 54]]


# This creates an error because the shape (2,1) cannot broadcast correctly with r_4 shape (4,5).
print(r_4 + np.array([[1], [1]]))

Broadcasting allows NumPy to combine arrays with different shapes when their dimensions are compatible. Smaller arrays can be stretched across larger arrays during the operation. The resulting shape usually follows the larger array when broadcasting is possible.

## Rounding

In [53]:
print(r_3)

[[0.80698105]
 [0.60110531]]


In [54]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [55]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [56]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [57]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [58]:
print(np.round(r_3, 2))

[[0.81]
 [0.6 ]]


## Cumulative Operations

In [59]:
print(r_4)

[[94 67 88 94 93]
 [45 38 61 69 44]
 [53 72 61 37 71]
 [77 75 78 86 53]]


In [60]:
print(np.sum(r_4))

1356


In [61]:
print(np.sum(r_4, axis=0))

[269 252 288 286 261]


In [62]:
print(np.sum(r_4, axis=1))

[436 257 294 369]


In [63]:
print(np.cumsum(r_4))

[  94  161  249  343  436  481  519  580  649  693  746  818  879  916
  987 1064 1139 1217 1303 1356]


In [64]:
print(np.cumsum(r_4, axis=0))

[[ 94  67  88  94  93]
 [139 105 149 163 137]
 [192 177 210 200 208]
 [269 252 288 286 261]]


## Grocery Problem

In [65]:
# Order: vegetables, fruits, snacks, beverages

bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [66]:
bag1_total = np.sum(bag1)
bag2_total = np.sum(bag2)

print(f"The first bag contains {bag1_total} items, and the second bag contains {bag2_total} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [67]:
category_totals = bag1 + bag2

print(f"There are {category_totals[0]} vegetables, {category_totals[1]} fruits, {category_totals[2]} boxes of snacks, and {category_totals[3]} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [68]:
ali = np.array([5, 4, 6, 4, 2])
ben = np.array([0, 5, 5, 3, 4])
carla = np.array([3, 6, 0, 3, 4])

print(ali)
print(ben)
print(carla)

[5 4 6 4 2]
[0 5 5 3 4]
[3 6 0 3 4]


In [69]:
all_knocks = np.array([ali, ben, carla])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [70]:
person_totals = np.sum(all_knocks, axis=1)
group_total = np.sum(all_knocks)

print(f"Ali knocked on {person_totals[0]} doors.")
print(f"Ben knocked on {person_totals[1]} doors.")
print(f"Carla knocked on {person_totals[2]} doors.")
print(f"The group knocked on {group_total} doors total.")

Ali knocked on 21 doors.
Ben knocked on 17 doors.
Carla knocked on 16 doors.
The group knocked on 54 doors total.


In [71]:
daily_totals = np.sum(all_knocks, axis=0)
rolling_total = np.cumsum(daily_totals)
estimated_votes = rolling_total * 0.5

print(estimated_votes)

[ 4.  11.5 17.  22.  27. ]
